sources:
  - /images/crud-annotated-document-print.png
  - /images/crud-annotated-document.png
  - /images/crud-annotated-document.rst
  - /includes/fact-unix-data-and-log-dir.rst
  - /includes/install-copy-release-linux-i686.rst
  - /includes/install-copy-release-linux-i686.rst
  - /includes/install-copy-release-linux-x86_64.rst
  - /includes/install-copy-release-osx-x86_64.rst
  - /includes/install-curl-release-ent-amzn64.rst
  - /includes/install-curl-release-ent-rhel62.rst
  - /includes/install-curl-release-ent-suse11.rst
  - /includes/install-curl-release-ent-ubuntu1204.rst
  - /includes/install-curl-release-linux-i686.rst
  - /includes/install-curl-release-linux-i686.rst
  - /includes/install-curl-release-linux-x86_64.rst
  - /includes/install-curl-release-osx-x86_64.rst
  - /includes/install-untar-release-linux-i686.rst
  - /includes/install-untar-release-linux-i686.rst
  - /includes/install-untar-release-linux-x86_64.rst
  - /includes/install-untar-release-osx-x86_64.rst
  - /includes/steps-install-configure-debian-packages.yaml
  - /includes/steps-install-on-linux-32.yaml
  - /includes/steps-install-on-linux-64.yaml
  - /includes/steps-install-on-linux.yaml
  - /includes/steps-install-osx-manual.yaml
  - /includes/steps-install-set-up-dbpath-osx.yaml
  - /includes/steps-install-set-up-dbpath.yaml
  - /includes/toc-installation-enterprise.yaml
  - /includes/toc-installation-linux.yaml
  - /includes/toc-installation-osx.yaml
  - /includes/toc-installation-windows.yaml
  - /includes/toc-spec-installation-linux-other.yaml
  - /includes/toc-spec-installation-linux-packages.yaml
  - /tutorial/install-mongodb-on-debian.txt
  - /tutorial/install-mongodb-on-linux.txt
  - /tutorial/install-mongodb-on-os-x.txt
  - /tutorial/install-mongodb-on-ubuntu.txt
---
source: /core/introduction.txt
target: /introduction.rst
---
source: /administration/install-enterprise.txt
target: /tutorial/install-enterprise.rst
...
