fr:
  inherit: base
es:
  inherit: base
ja:
  inherit: base
zh:
  inherit: base
it:
  inherit: base
base:
  targets:
    - 'latex'
    - 'json'
    - 'singlehtml'
    - 'html'
    - 'man'
    - 'epub'
    - 'dirhtml'
  doc-root:
    # - 'manual'
    - 'sitemap.xml'
    - 'osd.xml'
    - '.htaccess'
    - '10gen-gpg-key.asc'
    - '10gen-security-gpg-key.asc'
  branch-root: null
...