# The items in the ``builders`` list are the name of Sphinx builders
# supported by ``sphinx-build``.
#
# The ``prerequsites`` list stores all targets that must build before
# sphinx can begin.
#
# The ``generated-source`` list stores all the targets that generate rst.

prerequisites:
  - setup
  - generate-source
generated-source:
  - tables
  - api
  - toc
  - releases
  - generate-manpages
  - intersphinx
  - images
  - composites
web-base:
  excluded_files:
    - meta/reference
    - meta/use-cases
    - meta/administration
    - meta/manual
  tags:
    - web
dirhtml:
  inherit: web-base
html:
  inherit: web-base
latex:
  tags:
    - print
epub:
  tags:
    - print
singlehtml:
  tags:
    - web
man:
  tags:
    - manpage
gettext:
  tags:
    - print
    - web
    - manpage
json:
  tags:
    - print
    - web
    - manpage
linkcheck:
  tags:
    - web
texinfo:
  tags:
    - print
html-fr:
  builder: html
  inherit: html
  language: fr
html-es:
  builder: html
  inherit: html
  language: es
html-ja:
  builder: html
  inherit: html
  language: ja
html-it:
  builder: html
  inherit: html
  language: it
html-zh:
  builder: html
  inherit: html
  language: zh
...